### ISSUE TITLE
Open Main menu dropdown outside viewport

### ISSUE THREAD

**Issue by sottwell** [modxcms/a11y#30]
Main menu dropdowns that are longer than the screen height don't scroll, have to zoom out the browser to be able to get to the bottom entries of the admin menu (very small text)

**Comment by dubrod** [comment]
from what i've been told before we can not change things that are part of this `lexicon` like the menu. so open to suggestions on how we can alter the menus to make them shorter without sacrificing font size

**Comment by sottwell** [comment]
Not a matter of making them shorter, it's a matter of making them scrollable.

**Comment by dubrod** [comment]
can you implement that?

**Comment by sottwell** [comment]
Me? Wouldn't know where to begin.

**Comment by TheBoxer** [comment]
It's not problem just of a11y project, but in each MODX install.

btw. @rthrash not sure why I am assigned, it's html/css issue :)

**Comment by rthrash** [comment]
I could be wrong, but I think the menus are being built taller than the viewport and due to their positioning are not scrollable. Can add scrolling via CSS, but cannot handle the ExtJS parts that build the menus without taking the viewport height into account.

This definitely applies to all themes, and I've tagged this one `port to default` as such. It probably makes more sense to fix in 2.3.x and have it be part of this by default.

**Comment by TheBoxer** [comment]
Menus are not build via ExtJS, but it `header` controller, in PHP. So it's pure HTML (at least I hope so).

And yes, it should be fixed in 2.3.x, annoying bug...

**Comment by rthrash** [comment]
I think it's going to require some JS, because of absolute positioning. Maybe we can try something like: http://stackoverflow.com/questions/11512032/detect-if-dropdown-navigation-would-go-off-screen-and-reposition-it

**Comment by dubrod** [comment]
![2-column-submenu](https://cloud.githubusercontent.com/assets/595788/9388207/09c7dae4-4732-11e5-9e2c-07314e334650.jpeg)

this solution is ready for some testing
